name: CI - Ubuntu Linux
on: [push, pull_request]

jobs:
  test-ubuntu:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [
            "3.13",
            "3.14",
        ]
    steps:
      - uses: actions/checkout@v4
      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true
      - name: Set up Python
        run: uv python install ${{ matrix.python-version }}
      - name: Install the project
        run: uv sync --all-extras --dev
        env:
          UV_PYTHON: ${{ matrix.python-version }}
      - name: Test
        run: |
          uv run python -m unittest discover -v --pattern="*test.py" --start-directory tests
        env:
          UV_PYTHON: ${{ matrix.python-version }}
